apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-app
  labels:
    app: tetris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: khayri99/tetris-game:v1
        ports:
        - containerPort: 3000
